namespace EldenRing.Data.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<EldenRing.WebMVC.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "EldenRing.WebMVC.Models.ApplicationDbContext";
        }

        protected override void Seed(EldenRing.WebMVC.Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.
            context.Locations.AddOrUpdate(l => l.LocationId, new Location() { LocationId = 1, Name = "Bridge of Sacrifice", Region = "Limgrave" },
            new Location() { LocationId = 2, Name = "Church of Dragon Communion", Region = "Limgrave" },
            new Location() { LocationId = 3, Name = "Church of Elleh", Region = "Limgrave" },
            new Location() { LocationId = 4, Name = "Coastal Cave", Region = "Limgrave" },
            new Location() { LocationId = 5, Name = "DeathTouched Catacombs", Region = "Limgrave" },
            new Location() { LocationId = 6, Name = "Divine Tower Of Limgrave", Region = "Limgrave" },
            new Location() { LocationId = 7, Name = "Dragon-Burnt Ruins", Region = "Limgrave" },
            new Location() { LocationId = 8, Name = "Eternal City", Region = "Limgrave" },
            new Location() { LocationId = 9, Name = "Forlorn Hound Evergaol", Region = "Limgrave" },
            new Location() { LocationId = 10, Name = "Fort Haight", Region = "Limgrave" },
            new Location() { LocationId = 11, Name = "FringeFolk Heros Grave", Region = "Limgrave" },
            new Location() { LocationId = 12, Name = "GateFront Ruins", Region = "Limgrave" },
            new Location() { LocationId = 13, Name = "GroveSide Cave", Region = "Limgrave" },
            new Location() { LocationId = 14, Name = "Highroad Cave", Region = "Limgrave" },
            new Location() { LocationId = 15, Name = "KingsRealm Ruins", Region = "Limgrave" },
            new Location() { LocationId = 16, Name = "Limgrave Tunnels", Region = "Limgrave" },
            new Location() { LocationId = 17, Name = "Minor Erdtree MistWood", Region = "Limgrave" },
            new Location() { LocationId = 18, Name = "MistWood", Region = "Limgrave" },
            new Location() { LocationId = 19, Name = "MistWood Ruins", Region = "Limgrave" },
            new Location() { LocationId = 20, Name = "MurkWater Catacombs", Region = "Limgrave" },
            new Location() { LocationId = 21, Name = "MurkWater Cave", Region = "Limgrave" },
            new Location() { LocationId = 22, Name = "Sofria River Well", Region = "Limgrave" },
            new Location() { LocationId = 23, Name = "StormFoot Catacombs", Region = "Limgrave" },
            new Location() { LocationId = 24, Name = "StormGate", Region = "Limgrave" },
            new Location() { LocationId = 25, Name = "StormHill", Region = "Limgrave" },
            new Location() { LocationId = 26, Name = "StormHill Evergaol", Region = "Limgrave" },
            new Location() { LocationId = 27, Name = "StormHill Shack", Region = "Limgrave" },
            new Location() { LocationId = 28, Name = "Stranded GraveYard", Region = "Limgrave" },
            new Location() { LocationId = 29, Name = "SummonWater Village", Region = "Limgrave" },
            new Location() { LocationId = 30, Name = "Third Church of Marika", Region = "Limgrave" },
            new Location() { LocationId = 31, Name = "Waypoint Ruins", Region = "Limgrave" },
            new Location() { LocationId = 32, Name = "Stormveil Castle", Region = "Limgrave" },
            new Location() { LocationId = 33, Name = "Ailing Village", Region = "Weeping Penninsula" },
            new Location() { LocationId = 34, Name = "Callu Baptismal Church", Region = "Weeping Penninsula" },
            new Location() { LocationId = 35, Name = "Castle Morne", Region = "Weeping Penninsula" },
            new Location() { LocationId = 36, Name = "Church of Pilgrimage", Region = "Weeping Penninsula" },
            new Location() { LocationId = 37, Name = "Demi-human Forest Ruins", Region = "Weeping Penninsula" },
            new Location() { LocationId = 38, Name = "Earthbore Cave", Region = "Weeping Penninsula" },
            new Location() { LocationId = 39, Name = "Forest Lookout Cave", Region = "Weeping Penninsula" },
            new Location() { LocationId = 40, Name = "Fourth Church of Marika", Region = "Weeping Penninsula" },
            new Location() { LocationId = 41, Name = "Impalers Catacombs", Region = "Weeping Penninsula" },
            new Location() { LocationId = 42, Name = "Isolated Merchants Shack", Region = "Weeping Penninsula" },
            new Location() { LocationId = 43, Name = "Minor Erdtree", Region = "Weeping Penninsula" },
            new Location() { LocationId = 44, Name = "Morne Tunnel", Region = "Weeping Penninsula" },
            new Location() { LocationId = 45, Name = "Oridys's Rise", Region = "Weeping Penninsula" },
            new Location() { LocationId = 46, Name = "TombSward Catacombs", Region = "Weeping Penninsula" },
            new Location() { LocationId = 47, Name = "TombSward Cave", Region = "Weeping Penninsula" },
            new Location() { LocationId = 48, Name = "TombSward Ruins", Region = "Weeping Penninsula" },
            new Location() { LocationId = 49, Name = "Tower of Return", Region = "Weeping Penninsula" },
            new Location() { LocationId = 50, Name = "Weeping Evergaol", Region = "Weeping Penninsula" },
            new Location() { LocationId = 51, Name = "WitchBane Ruins", Region = "Weeping Penninsula" },
            new Location() { LocationId = 52, Name = "Academy Crystal Cave", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 53, Name = "Academy Gate Town", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 54, Name = "Ainsel River Well", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 55, Name = "Artist Shack", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 56, Name = "Bellum Church", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 57, Name = "Bellum Highway", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 58, Name = "Black Knife Catacombs", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 59, Name = "Caria Manor", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 60, Name = "Carian Study Hall", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 61, Name = "Cathedral of Manus Celes", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 62, Name = "Chapel of Anticipation", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 63, Name = "Chelona's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 64, Name = "Church of Inhibition", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 65, Name = "Church of Irith", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 66, Name = "Church of Vows", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 67, Name = "CliffBottom Catacombs", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 68, Name = "Converted Fringe Tower", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 69, Name = "Converted Tower", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 70, Name = "Cuckoo's Evergaol", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 71, Name = "Deep Ainsel Well", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 72, Name = "Frenzied Flame Village", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 73, Name = "Grand Lift of Dectus", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 74, Name = "Highway Lookout Tower", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 75, Name = "Jarburg", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 76, Name = "Lakeside Crystal Cave", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 77, Name = "Laskyar Ruins", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 78, Name = "Lunar Estate Ruins", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 79, Name = "Malefactor's Evergaol", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 80, Name = "Minor ErdTree Liurnia SouthWest", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 81, Name = "MoonFolk Ruins", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 82, Name = "Purified Ruins", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 83, Name = "Ranni's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 84, Name = "Raya Lucaria Crystal Tunnel", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 85, Name = "Ranni's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 86, Name = "Revenger's Shack", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 87, Name = "RingLeader's Evergaol", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 88, Name = "Road's End Catacombs", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 89, Name = "Rose Church", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 90, Name = "Royal Grave Evergaol", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 91, Name = "Ruin-Strewn Precipice", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 92, Name = "Seluvis's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 93, Name = "Slumbering Wolf's Shack", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 94, Name = "StillWater Cave", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 95, Name = "Temple Quarter", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 96, Name = "Tetsu's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 97, Name = "The Four Belfries", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 98, Name = "Village of the Albinaurics", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 99, Name = "Raya Lucaria Academy", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 100, Name = "Hallowhorn Grounds", Region = "Siofra River" },
            new Location() { LocationId = 101, Name = "Night's Sacred Ground", Region = "Siofra River" },
            new Location() { LocationId = 102, Name = "Nokron", Region = "Siofra River" },
            new Location() { LocationId = 103, Name = "Siofra Aqueduct", Region = "Siofra River" },
            new Location() { LocationId = 104, Name = "Nokstella", Region = "Ainsel River" },
            new Location() { LocationId = 105, Name = "Uhl Palace Ruins", Region = "Ainsel River" },
            new Location() { LocationId = 106, Name = "Altus Tunnel", Region = "Altus Plateau" },
            new Location() { LocationId = 107, Name = "Auriza Hero's Grave", Region = "Altus Plateau" },
            new Location() { LocationId = 108, Name = "Capital Outskirts", Region = "Altus Plateau" },
            new Location() { LocationId = 109, Name = "Divine Tower of West Altus", Region = "Altus Plateau" },
            new Location() { LocationId = 110, Name = "Dominula the Windmill Village", Region = "Altus Plateau" },
            new Location() { LocationId = 111, Name = "East Windmill Pasture", Region = "Altus Plateau" },
            new Location() { LocationId = 112, Name = "Golden Lineage Evergaol", Region = "Altus Plateau" },
            new Location() { LocationId = 113, Name = "Lux Ruins", Region = "Altus Plateau" },
            new Location() { LocationId = 114, Name = "Minor ErdTree Church", Region = "Altus Plateau" },
            new Location() { LocationId = 115, Name = "Old Altus Tunnel", Region = "Altus Plateau" },
            new Location() { LocationId = 116, Name = "Sealed Tunnel", Region = "Altus Plateau" },
            new Location() { LocationId = 117, Name = "The Shaded Castle", Region = "Altus Plateau" },
            new Location() { LocationId = 118, Name = "WoodFolk Ruins", Region = "Altus Plateau" },
            new Location() { LocationId = 119, Name = "Writheblood Ruins", Region = "Altus Plateau" },
            new Location() { LocationId = 120, Name = "Aeonia Swamp", Region = "Caelid" },
            new Location() { LocationId = 121, Name = "Caelem Ruins", Region = "Caelid" },
            new Location() { LocationId = 122, Name = "Caelid Waypoint Ruins", Region = "Caelid" },
            new Location() { LocationId = 123, Name = "Cathedral of Dragon Communion Caelid", Region = "Caelid" },
            new Location() { LocationId = 124, Name = "Church of The Plague", Region = "Caelid" },
            new Location() { LocationId = 125, Name = "Forsaken Ruins", Region = "Caelid" },
            new Location() { LocationId = 126, Name = "Fort Gael", Region = "Caelid" },
            new Location() { LocationId = 127, Name = "Gael Tunnel", Region = "Caelid" },
            new Location() { LocationId = 128, Name = "Gaol Cave", Region = "Caelid" },
            new Location() { LocationId = 129, Name = "Gowry's Shack", Region = "Caelid" },
            new Location() { LocationId = 130, Name = "Minor ErdTree Caelid", Region = "Caelid" },
            new Location() { LocationId = 131, Name = "Minor ErdTree Catacombs", Region = "Caelid" },
            new Location() { LocationId = 132, Name = "Redmane Castle", Region = "Caelid" },
            new Location() { LocationId = 133, Name = "Sellia Gateway", Region = "Caelid" },
            new Location() { LocationId = 134, Name = "Sellia Town of Sorcery", Region = "Caelid" },
            new Location() { LocationId = 136, Name = "Shack of The Rotting", Region = "Caelid" },
            new Location() { LocationId = 137, Name = "Smoldering Church", Region = "Caelid" },
            new Location() { LocationId = 138, Name = "Street of Sages Ruins", Region = "Caelid" },
            new Location() { LocationId = 139, Name = "War-Dead Catacombs", Region = "Caelid" },
            new Location() { LocationId = 140, Name = "Corpse-Stench Shack", Region = "Mt. Gemlir" },
            new Location() { LocationId = 141, Name = "Craftsman's Shack", Region = "Mt. Gemlir" },
            new Location() { LocationId = 142, Name = "Fort Laiedd", Region = "Mt. Gemlir" },
            new Location() { LocationId = 143, Name = "Gelmir Hero's Grave", Region = "Mt. Gemlir" },
            new Location() { LocationId = 144, Name = "Hermit Village", Region = "Mt. Gemlir" },
            new Location() { LocationId = 145, Name = "Hermit's Shack", Region = "Mt. Gemlir" },
            new Location() { LocationId = 146, Name = "Perfumer'S Ruin", Region = "Mt. Gemlir" },
            new Location() { LocationId = 147, Name = "Second Church of Marika", Region = "Mt. Gemlir" },
            new Location() { LocationId = 148, Name = "SeetheWater Cave", Region = "Mt. Gemlir" },
            new Location() { LocationId = 149, Name = "Unsightly Catacombs", Region = "Mt. Gemlir" },
            new Location() { LocationId = 150, Name = "Volcano Manor", Region = "Mt. Gemlir" },
            new Location() { LocationId = 151, Name = "Wyndham Catacombs", Region = "Mt. Gemlir" },
            new Location() { LocationId = 152, Name = "Wyndham Ruins", Region = "Mt. Gemlir" },
            new Location() { LocationId = 153, Name = "Bestial Sanctum", Region = "DragonBarrow" },
            new Location() { LocationId = 154, Name = "Deep Siofra Well", Region = "DragonBarrow" },
            new Location() { LocationId = 155, Name = "Divine Tower of Caelid", Region = "DragonBarrow" },
            new Location() { LocationId = 156, Name = "DragonBarrow Cave", Region = "DragonBarrow" },
            new Location() { LocationId = 157, Name = "Fort Faroth", Region = "DragonBarrow" },
            new Location() { LocationId = 158, Name = "Isolated Merchant's Shack DB", Region = "DragonBarrow" },
            new Location() { LocationId = 159, Name = "Lenne's Rise", Region = "DragonBarrow" },
            new Location() { LocationId = 160, Name = "Sellia Crystal Tunnel", Region = "DragonBarrow" },
            new Location() { LocationId = 161, Name = "Grand Cloister", Region = "Lake of Rot" },
            new Location() { LocationId = 162, Name = "Subterranean Shunning-Grounds", Region = "Leyndell, Royal Capital" },
            new Location() { LocationId = 163, Name = "Albinauric Rise", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 164, Name = "Apostate Derelict", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 165, Name = "Consecrated SnowField Catacombs", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 166, Name = "Elphael, Brace of The Haligtree", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 167, Name = "Yelough Anix Ruins", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 168, Name = "Yelough Anix Tunnel", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 169, Name = "Mohgwyn Dynasty Mausoleum", Region = "Mohgwyn Palace" },
            new Location() { LocationId = 170, Name = "Castle Sol", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 171, Name = "Church of Repose", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 172, Name = "First Church of Marika", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 173, Name = "Forge of The Giants", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 174, Name = "Giant-Conquering Hero's Grave", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 175, Name = "Grand Lift of Rold", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 176, Name = "Guardian's Garrison", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 177, Name = "Heretical Rise", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 178, Name = "Lord Contender's Evergaol", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 179, Name = "Shack of The Lofty", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 180, Name = "SpiritCaller's Cave", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 181, Name = "StarGazer's Ruins", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 182, Name = "Zamor Ruins", Region = "Mountaintops of The Giants" }
            );
            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.
        }
    }
}
