namespace EldenRing.Data.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.IO;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<EldenRing.WebMVC.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "EldenRing.WebMVC.Models.ApplicationDbContext";
        }

        protected override void Seed(EldenRing.WebMVC.Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.
            context.Locations.AddOrUpdate(l => l.LocationId, new Location() { LocationId = 1, Name = "Bridge of Sacrifice", Region = "Limgrave" },
            new Location() { LocationId = 2, Name = "Church of Dragon Communion", Region = "Limgrave" },
            new Location() { LocationId = 3, Name = "Church of Elleh", Region = "Limgrave" },
            new Location() { LocationId = 4, Name = "Coastal Cave", Region = "Limgrave" },
            new Location() { LocationId = 5, Name = "DeathTouched Catacombs", Region = "Limgrave" },
            new Location() { LocationId = 6, Name = "Divine Tower Of Limgrave", Region = "Limgrave" },
            new Location() { LocationId = 7, Name = "Dragon-Burnt Ruins", Region = "Limgrave" },
            new Location() { LocationId = 8, Name = "Eternal City", Region = "Limgrave" },
            new Location() { LocationId = 9, Name = "Forlorn Hound Evergaol", Region = "Limgrave" },
            new Location() { LocationId = 10, Name = "Fort Haight", Region = "Limgrave" },
            new Location() { LocationId = 11, Name = "FringeFolk Heros Grave", Region = "Limgrave" },
            new Location() { LocationId = 12, Name = "GateFront Ruins", Region = "Limgrave" },
            new Location() { LocationId = 13, Name = "GroveSide Cave", Region = "Limgrave" },
            new Location() { LocationId = 14, Name = "Highroad Cave", Region = "Limgrave" },
            new Location() { LocationId = 15, Name = "KingsRealm Ruins", Region = "Limgrave" },
            new Location() { LocationId = 16, Name = "Limgrave Tunnels", Region = "Limgrave" },
            new Location() { LocationId = 17, Name = "Minor Erdtree MistWood", Region = "Limgrave" },
            new Location() { LocationId = 18, Name = "MistWood", Region = "Limgrave" },
            new Location() { LocationId = 19, Name = "MistWood Ruins", Region = "Limgrave" },
            new Location() { LocationId = 20, Name = "MurkWater Catacombs", Region = "Limgrave" },
            new Location() { LocationId = 21, Name = "MurkWater Cave", Region = "Limgrave" },
            new Location() { LocationId = 22, Name = "Sofria River Well", Region = "Limgrave" },
            new Location() { LocationId = 23, Name = "StormFoot Catacombs", Region = "Limgrave" },
            new Location() { LocationId = 24, Name = "StormGate", Region = "Limgrave" },
            new Location() { LocationId = 25, Name = "StormHill", Region = "Limgrave" },
            new Location() { LocationId = 26, Name = "StormHill Evergaol", Region = "Limgrave" },
            new Location() { LocationId = 27, Name = "StormHill Shack", Region = "Limgrave" },
            new Location() { LocationId = 28, Name = "Stranded GraveYard", Region = "Limgrave" },
            new Location() { LocationId = 29, Name = "SummonWater Village", Region = "Limgrave" },
            new Location() { LocationId = 30, Name = "Third Church of Marika", Region = "Limgrave" },
            new Location() { LocationId = 31, Name = "Waypoint Ruins", Region = "Limgrave" },
            new Location() { LocationId = 32, Name = "Stormveil Castle", Region = "Limgrave" },
            new Location() { LocationId = 33, Name = "Ailing Village", Region = "Weeping Penninsula" },
            new Location() { LocationId = 34, Name = "Callu Baptismal Church", Region = "Weeping Penninsula" },
            new Location() { LocationId = 35, Name = "Castle Morne", Region = "Weeping Penninsula" },
            new Location() { LocationId = 36, Name = "Church of Pilgrimage", Region = "Weeping Penninsula" },
            new Location() { LocationId = 37, Name = "Demi-human Forest Ruins", Region = "Weeping Penninsula" },
            new Location() { LocationId = 38, Name = "Earthbore Cave", Region = "Weeping Penninsula" },
            new Location() { LocationId = 39, Name = "Forest Lookout Cave", Region = "Weeping Penninsula" },
            new Location() { LocationId = 40, Name = "Fourth Church of Marika", Region = "Weeping Penninsula" },
            new Location() { LocationId = 41, Name = "Impalers Catacombs", Region = "Weeping Penninsula" },
            new Location() { LocationId = 42, Name = "Isolated Merchants Shack", Region = "Weeping Penninsula" },
            new Location() { LocationId = 43, Name = "Minor Erdtree", Region = "Weeping Penninsula" },
            new Location() { LocationId = 44, Name = "Morne Tunnel", Region = "Weeping Penninsula" },
            new Location() { LocationId = 45, Name = "Oridys's Rise", Region = "Weeping Penninsula" },
            new Location() { LocationId = 46, Name = "TombSward Catacombs", Region = "Weeping Penninsula" },
            new Location() { LocationId = 47, Name = "TombSward Cave", Region = "Weeping Penninsula" },
            new Location() { LocationId = 48, Name = "TombSward Ruins", Region = "Weeping Penninsula" },
            new Location() { LocationId = 49, Name = "Tower of Return", Region = "Weeping Penninsula" },
            new Location() { LocationId = 50, Name = "Weeping Evergaol", Region = "Weeping Penninsula" },
            new Location() { LocationId = 51, Name = "WitchBane Ruins", Region = "Weeping Penninsula" },
            new Location() { LocationId = 52, Name = "Academy Crystal Cave", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 53, Name = "Academy Gate Town", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 54, Name = "Ainsel River Well", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 55, Name = "Artist Shack", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 56, Name = "Bellum Church", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 57, Name = "Bellum Highway", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 58, Name = "Black Knife Catacombs", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 59, Name = "Caria Manor", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 60, Name = "Carian Study Hall", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 61, Name = "Cathedral of Manus Celes", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 62, Name = "Chapel of Anticipation", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 63, Name = "Chelona's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 64, Name = "Church of Inhibition", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 65, Name = "Church of Irith", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 66, Name = "Church of Vows", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 67, Name = "CliffBottom Catacombs", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 68, Name = "Converted Fringe Tower", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 69, Name = "Converted Tower", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 70, Name = "Cuckoo's Evergaol", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 71, Name = "Deep Ainsel Well", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 72, Name = "Frenzied Flame Village", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 73, Name = "Grand Lift of Dectus", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 74, Name = "Highway Lookout Tower", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 75, Name = "Jarburg", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 76, Name = "Lakeside Crystal Cave", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 77, Name = "Laskyar Ruins", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 78, Name = "Lunar Estate Ruins", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 79, Name = "Malefactor's Evergaol", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 80, Name = "Minor ErdTree Liurnia SouthWest", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 81, Name = "MoonFolk Ruins", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 82, Name = "Purified Ruins", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 83, Name = "Ranni's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 84, Name = "Raya Lucaria Crystal Tunnel", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 85, Name = "Ranni's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 86, Name = "Revenger's Shack", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 87, Name = "RingLeader's Evergaol", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 88, Name = "Road's End Catacombs", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 89, Name = "Rose Church", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 90, Name = "Royal Grave Evergaol", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 91, Name = "Ruin-Strewn Precipice", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 92, Name = "Seluvis's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 93, Name = "Slumbering Wolf's Shack", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 94, Name = "StillWater Cave", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 95, Name = "Temple Quarter", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 96, Name = "Tetsu's Rise", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 97, Name = "The Four Belfries", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 98, Name = "Village of the Albinaurics", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 99, Name = "Raya Lucaria Academy", Region = "Liurnia of The Lakes" },
            new Location() { LocationId = 100, Name = "Hallowhorn Grounds", Region = "Siofra River" },
            new Location() { LocationId = 101, Name = "Night's Sacred Ground", Region = "Siofra River" },
            new Location() { LocationId = 102, Name = "Nokron", Region = "Siofra River" },
            new Location() { LocationId = 103, Name = "Siofra Aqueduct", Region = "Siofra River" },
            new Location() { LocationId = 104, Name = "Nokstella", Region = "Ainsel River" },
            new Location() { LocationId = 105, Name = "Uhl Palace Ruins", Region = "Ainsel River" },
            new Location() { LocationId = 106, Name = "Altus Tunnel", Region = "Altus Plateau" },
            new Location() { LocationId = 107, Name = "Auriza Hero's Grave", Region = "Altus Plateau" },
            new Location() { LocationId = 108, Name = "Capital Outskirts", Region = "Altus Plateau" },
            new Location() { LocationId = 109, Name = "Divine Tower of West Altus", Region = "Altus Plateau" },
            new Location() { LocationId = 110, Name = "Dominula the Windmill Village", Region = "Altus Plateau" },
            new Location() { LocationId = 111, Name = "East Windmill Pasture", Region = "Altus Plateau" },
            new Location() { LocationId = 112, Name = "Golden Lineage Evergaol", Region = "Altus Plateau" },
            new Location() { LocationId = 113, Name = "Lux Ruins", Region = "Altus Plateau" },
            new Location() { LocationId = 114, Name = "Minor ErdTree Church", Region = "Altus Plateau" },
            new Location() { LocationId = 115, Name = "Old Altus Tunnel", Region = "Altus Plateau" },
            new Location() { LocationId = 116, Name = "Sealed Tunnel", Region = "Altus Plateau" },
            new Location() { LocationId = 117, Name = "The Shaded Castle", Region = "Altus Plateau" },
            new Location() { LocationId = 118, Name = "WoodFolk Ruins", Region = "Altus Plateau" },
            new Location() { LocationId = 119, Name = "Writheblood Ruins", Region = "Altus Plateau" },
            new Location() { LocationId = 120, Name = "Aeonia Swamp", Region = "Caelid" },
            new Location() { LocationId = 121, Name = "Caelem Ruins", Region = "Caelid" },
            new Location() { LocationId = 122, Name = "Caelid Waypoint Ruins", Region = "Caelid" },
            new Location() { LocationId = 123, Name = "Cathedral of Dragon Communion Caelid", Region = "Caelid" },
            new Location() { LocationId = 124, Name = "Church of The Plague", Region = "Caelid" },
            new Location() { LocationId = 125, Name = "Forsaken Ruins", Region = "Caelid" },
            new Location() { LocationId = 126, Name = "Fort Gael", Region = "Caelid" },
            new Location() { LocationId = 127, Name = "Gael Tunnel", Region = "Caelid" },
            new Location() { LocationId = 128, Name = "Gaol Cave", Region = "Caelid" },
            new Location() { LocationId = 129, Name = "Gowry's Shack", Region = "Caelid" },
            new Location() { LocationId = 130, Name = "Minor ErdTree Caelid", Region = "Caelid" },
            new Location() { LocationId = 131, Name = "Minor ErdTree Catacombs", Region = "Caelid" },
            new Location() { LocationId = 132, Name = "Redmane Castle", Region = "Caelid" },
            new Location() { LocationId = 133, Name = "Sellia Gateway", Region = "Caelid" },
            new Location() { LocationId = 134, Name = "Sellia Town of Sorcery", Region = "Caelid" },
            new Location() { LocationId = 136, Name = "Shack of The Rotting", Region = "Caelid" },
            new Location() { LocationId = 137, Name = "Smoldering Church", Region = "Caelid" },
            new Location() { LocationId = 138, Name = "Street of Sages Ruins", Region = "Caelid" },
            new Location() { LocationId = 139, Name = "War-Dead Catacombs", Region = "Caelid" },
            new Location() { LocationId = 140, Name = "Corpse-Stench Shack", Region = "Mt. Gemlir" },
            new Location() { LocationId = 141, Name = "Craftsman's Shack", Region = "Mt. Gemlir" },
            new Location() { LocationId = 142, Name = "Fort Laiedd", Region = "Mt. Gemlir" },
            new Location() { LocationId = 143, Name = "Gelmir Hero's Grave", Region = "Mt. Gemlir" },
            new Location() { LocationId = 144, Name = "Hermit Village", Region = "Mt. Gemlir" },
            new Location() { LocationId = 145, Name = "Hermit's Shack", Region = "Mt. Gemlir" },
            new Location() { LocationId = 146, Name = "Perfumer'S Ruin", Region = "Mt. Gemlir" },
            new Location() { LocationId = 147, Name = "Second Church of Marika", Region = "Mt. Gemlir" },
            new Location() { LocationId = 148, Name = "SeetheWater Cave", Region = "Mt. Gemlir" },
            new Location() { LocationId = 149, Name = "Unsightly Catacombs", Region = "Mt. Gemlir" },
            new Location() { LocationId = 150, Name = "Volcano Manor", Region = "Mt. Gemlir" },
            new Location() { LocationId = 151, Name = "Wyndham Catacombs", Region = "Mt. Gemlir" },
            new Location() { LocationId = 152, Name = "Wyndham Ruins", Region = "Mt. Gemlir" },
            new Location() { LocationId = 153, Name = "Bestial Sanctum", Region = "DragonBarrow" },
            new Location() { LocationId = 154, Name = "Deep Siofra Well", Region = "DragonBarrow" },
            new Location() { LocationId = 155, Name = "Divine Tower of Caelid", Region = "DragonBarrow" },
            new Location() { LocationId = 156, Name = "DragonBarrow Cave", Region = "DragonBarrow" },
            new Location() { LocationId = 157, Name = "Fort Faroth", Region = "DragonBarrow" },
            new Location() { LocationId = 158, Name = "Isolated Merchant's Shack DB", Region = "DragonBarrow" },
            new Location() { LocationId = 159, Name = "Lenne's Rise", Region = "DragonBarrow" },
            new Location() { LocationId = 160, Name = "Sellia Crystal Tunnel", Region = "DragonBarrow" },
            new Location() { LocationId = 161, Name = "Grand Cloister", Region = "Lake of Rot" },
            new Location() { LocationId = 162, Name = "Subterranean Shunning-Grounds", Region = "Leyndell, Royal Capital" },
            new Location() { LocationId = 184, Name = "ErdTree Sanctuary", Region = "Leyndell, Royal Capital" },
            new Location() { LocationId = 163, Name = "Albinauric Rise", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 164, Name = "Apostate Derelict", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 165, Name = "Consecrated SnowField Catacombs", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 166, Name = "Elphael, Brace of The Haligtree", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 167, Name = "Yelough Anix Ruins", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 168, Name = "Yelough Anix Tunnel", Region = "Consecrated Snowfield" },
            new Location() { LocationId = 169, Name = "Mohgwyn Dynasty Mausoleum", Region = "Mohgwyn Palace" },
            new Location() { LocationId = 170, Name = "Castle Sol", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 171, Name = "Church of Repose", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 172, Name = "First Church of Marika", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 173, Name = "Forge of The Giants", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 174, Name = "Giant-Conquering Hero's Grave", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 175, Name = "Grand Lift of Rold", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 176, Name = "Guardian's Garrison", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 177, Name = "Heretical Rise", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 178, Name = "Lord Contender's Evergaol", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 179, Name = "Shack of The Lofty", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 180, Name = "SpiritCaller's Cave", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 181, Name = "StarGazer's Ruins", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 182, Name = "Zamor Ruins", Region = "Mountaintops of The Giants" },
            new Location() { LocationId = 183, Name = "Roundtable hold", Region = "N/A" },
            new Location() { LocationId = 185, Name = "N/A", Region = "N/A" }
            );
            context.Spells.AddOrUpdate(s => s.SpellId, new Spell() { SpellId = 1, Name = "Black Blade", TypeOfSpell = SpellType.Magic, Incantation = true, Scorcery = false, FocusPoints = 26, SlotUsage = 2, IntelligenceScaling = 0, FaithScaling = 46, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Black Blade.png")},
            new Spell() { SpellId = 2, Name = "Bloodboon", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 15, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 14, ArcaneScaling = 17, LocationId = 183, Image = File.ReadAllBytes("Images/BloodBoon.png") },
            new Spell() { SpellId = 3, Name = "Burn O Flame", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 30, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 27, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Burn O Flame!.png") },
            new Spell() { SpellId = 4, Name = "Carian Retaliation", TypeOfSpell = SpellType.Fire, Incantation = false, Scorcery = true, FocusPoints = 8, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 17, ArcaneScaling = 0, LocationId = 92, Image = File.ReadAllBytes("Images/Carian Retaliation.png") },
            new Spell() { SpellId = 5, Name = "Comet Azur", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = true, FocusPoints = 40, SlotUsage = 3, IntelligenceScaling = 60, FaithScaling = 0, ArcaneScaling = 0, LocationId = 144, Image = File.ReadAllBytes("Images/Comet Azur.png") },
            new Spell() { SpellId = 6, Name = "Death Lightning", TypeOfSpell = SpellType.Blight, Incantation = true, Scorcery = false, FocusPoints = 46, SlotUsage = 2, IntelligenceScaling = 0, FaithScaling = 47, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Death Lightning.png") },
            new Spell() { SpellId = 7, Name = "Elden Stars", TypeOfSpell = SpellType.Magic, Incantation = true, Scorcery = false, FocusPoints = 47, SlotUsage = 2, IntelligenceScaling = 0, FaithScaling = 50, ArcaneScaling = 0, LocationId = 162, Image = File.ReadAllBytes("Images/Elden Stars.png") },
            new Spell() { SpellId = 8, Name = "Eternal Darkness", TypeOfSpell = SpellType.Debuff, Incantation = false, Scorcery = true, FocusPoints = 25, SlotUsage = 1, IntelligenceScaling = 35, FaithScaling = 0, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Eternal Darkness.png") },
            new Spell() { SpellId = 9, Name = "Flame Fortification", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 20, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 10, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Flame Fortification.png") },
            new Spell() { SpellId = 10, Name = "Fortissax's Lightning Spear", TypeOfSpell = SpellType.Lightning, Incantation = true, Scorcery = false, FocusPoints = 64, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 46, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Fortissax's Lightning Spear.png") },
            new Spell() { SpellId = 11, Name = "Golden Vow", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 47, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 25, ArcaneScaling = 0, LocationId = 140, Image = File.ReadAllBytes("Images/Golden Vow.png") },
            new Spell() { SpellId = 12, Name = "Placidusax's Ruin", TypeOfSpell = SpellType.Magic, Incantation = true, Scorcery = false, FocusPoints = 62, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 36, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Placidusax's Ruin.png") },
            new Spell() { SpellId = 13, Name = "Protection of the ErdTree", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 30, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 35, ArcaneScaling = 0, LocationId = 119, Image = File.ReadAllBytes("Images/Protection of the Erdtree.png") },
            new Spell() { SpellId = 14, Name = "Ranni's Dark Moon", TypeOfSpell = SpellType.Debuff, Incantation = false, Scorcery = true, FocusPoints = 62, SlotUsage = 2, IntelligenceScaling = 68, FaithScaling = 0, ArcaneScaling = 0, LocationId = 63, Image = File.ReadAllBytes("Images/Ranni's Dark Moon.png") },
            new Spell() { SpellId = 14, Name = "Rennala's Full Moon", TypeOfSpell = SpellType.Debuff, Incantation = false, Scorcery = true, FocusPoints = 5, SlotUsage = 2, IntelligenceScaling = 70, FaithScaling = 0, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Rennala's Full Moon.png") },
            new Spell() { SpellId = 15, Name = "Rykard's Rancor", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = true, FocusPoints = 35, SlotUsage = 1, IntelligenceScaling = 40, FaithScaling = 18, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Rykard's Rancor.png") },
            new Spell() { SpellId = 16, Name = "Scarlet Aeonia", TypeOfSpell = SpellType.ScarletRot, Incantation = true, Scorcery = false, FocusPoints = 56, SlotUsage = 3, IntelligenceScaling = 0, FaithScaling = 35, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Scarlet Aeonia.png") },
            new Spell() { SpellId = 17, Name = "The Flame of Frenzy", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 16, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 14, ArcaneScaling = 17, LocationId = 183, Image = File.ReadAllBytes("Images/The Flame of Frenzy.png") },
            new Spell() { SpellId = 18, Name = "Agheel's Flame", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 15, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 16, ArcaneScaling = 0, LocationId = 34, Image = File.ReadAllBytes("Images/Agheel's Flame.png") },
            new Spell() { SpellId = 19, Name = "Ambush Shard", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = true, FocusPoints = 16, SlotUsage = 1, IntelligenceScaling = 23, FaithScaling = 0, ArcaneScaling = 0, LocationId = 51, Image = File.ReadAllBytes("Images/Ambush Shard.png") },
            new Spell() { SpellId = 20, Name = "Assassin's Approach", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 15, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 10, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Assassin's Approach.png") },
            new Spell() { SpellId = 21, Name = "Divine Fortification", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 20, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 10, ArcaneScaling = 0, LocationId = 48, Image = File.ReadAllBytes("Images/Divine Fortification.png") },
            new Spell() { SpellId = 22, Name = "Dragon Fire", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 28, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 15, ArcaneScaling = 12, LocationId = 2, Image = File.ReadAllBytes("Images/Dragonfire.png") },
            new Spell() { SpellId = 23, Name = "Ekzykes's Decay", TypeOfSpell = SpellType.ScarletRot, Incantation = true, Scorcery = false, FocusPoints = 48, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 23, ArcaneScaling = 15, LocationId = 123, Image = File.ReadAllBytes("Images/Ekzykes's Decay.png") },
            new Spell() { SpellId = 24, Name = "Electrify Armament", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 27, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 15, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Electrify Armament.png") },
            new Spell() { SpellId = 25, Name = "Flame Grant Me Strength", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 28, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 15, ArcaneScaling = 0, LocationId = 122, Image = File.ReadAllBytes("Images/Flame Grant me Strength.png") },
            new Spell() { SpellId = 26, Name = "Flame Protect Me", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 30, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 24, ArcaneScaling = 0, LocationId = 174, Image = File.ReadAllBytes("Images/Flame Protect Me.png") },
            new Spell() { SpellId = 27, Name = "Frozen Armament", TypeOfSpell = SpellType.Buff, Incantation = false, Scorcery = true, FocusPoints = 20, SlotUsage = 1, IntelligenceScaling = 15, FaithScaling = 0, ArcaneScaling = 0, LocationId = 59, Image = File.ReadAllBytes("Images/Frozen Armament.png") },
            new Spell() { SpellId = 28, Name = "GlintStone Arc", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = true, FocusPoints = 10, SlotUsage = 1, IntelligenceScaling = 13, FaithScaling = 0, ArcaneScaling = 0, LocationId = 31, Image = File.ReadAllBytes("Images/Glintstone Arc.png") },
            new Spell() { SpellId = 29, Name = "Gravity Well", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = true, FocusPoints = 12, SlotUsage = 1, IntelligenceScaling = 17, FaithScaling = 0, ArcaneScaling = 0, LocationId = 99, Image = File.ReadAllBytes("Images/Gravity Well.png") },
            new Spell() { SpellId = 30, Name = "Great Heal", TypeOfSpell = SpellType.Heal, Incantation = true, Scorcery = false, FocusPoints = 45, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 15, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Great Heal.png") },
            new Spell() { SpellId = 31, Name = "Lansseax's Glaive", TypeOfSpell = SpellType.Lightning, Incantation = true, Scorcery = false, FocusPoints = 35, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 40, ArcaneScaling = 0, LocationId = 113, Image = File.ReadAllBytes("Images/Lansseax's Glaive.png") },
            new Spell() { SpellId = 32, Name = "Law of Regression", TypeOfSpell = SpellType.Heal, Incantation = true, Scorcery = false, FocusPoints = 55, SlotUsage = 1, IntelligenceScaling = 37, FaithScaling = 0, ArcaneScaling = 0, LocationId = 184, Image = File.ReadAllBytes("Images/Law of Regression.png") },
            new Spell() { SpellId = 33, Name = "Lightning Spear", TypeOfSpell = SpellType.Lightning, Incantation = true, Scorcery = false, FocusPoints = 18, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 17, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Lightning Spear.png") },
            new Spell() { SpellId = 34, Name = "Litany of Proper Death", TypeOfSpell = SpellType.Holy, Incantation = true, Scorcery = false, FocusPoints = 17, SlotUsage = 1, IntelligenceScaling = 17, FaithScaling = 17, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Litany of Proper Death.png") },
            new Spell() { SpellId = 35, Name = "Lord's Aid", TypeOfSpell = SpellType.Heal, Incantation = true, Scorcery = false, FocusPoints = 9, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 12, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Lord's Aid.png") },
            new Spell() { SpellId = 36, Name = "Loretta's GreatBow", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = true, FocusPoints = 28, SlotUsage = 1, IntelligenceScaling = 26, FaithScaling = 0, ArcaneScaling = 0, LocationId = 59, Image = File.ReadAllBytes("Images/Loretta's Greatbow.png") },
            new Spell() { SpellId = 37, Name = "Magic GlintBlade", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = true, FocusPoints = 12, SlotUsage = 1, IntelligenceScaling = 14, FaithScaling = 0, ArcaneScaling = 0, LocationId = 66, Image = File.ReadAllBytes("Images/Magic Glintblade.png") },
            new Spell() { SpellId = 38, Name = "Order's Blade", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 22, SlotUsage = 1, IntelligenceScaling = 13, FaithScaling = 13, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Order's Blade.png") },
            new Spell() { SpellId = 39, Name = "Terra Magicus", TypeOfSpell = SpellType.Buff, Incantation = false, Scorcery = true, FocusPoints = 20, SlotUsage = 1, IntelligenceScaling = 20, FaithScaling = 0, ArcaneScaling = 0, LocationId = 52, Image = File.ReadAllBytes("Images/Terra Magicus.png") },
            new Spell() { SpellId = 40, Name = "Theodorix's Magma", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 45, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 21, ArcaneScaling = 14, LocationId = 163, Image = File.ReadAllBytes("Images/Theodorix's Magma.png") },
            new Spell() { SpellId = 41, Name = "Unseen Blade", TypeOfSpell = SpellType.Buff, Incantation = false, Scorcery = true, FocusPoints = 18, SlotUsage = 1, IntelligenceScaling = 12, FaithScaling = 0, ArcaneScaling = 0, LocationId = 115, Image = File.ReadAllBytes("Images/Unseen Blade.png") },
            new Spell() { SpellId = 42, Name = "Urgent Heal", TypeOfSpell = SpellType.Heal, Incantation = true, Scorcery = false, FocusPoints = 16, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 8, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Urgent Heal.png") },
            new Spell() { SpellId = 43, Name = "Vyke's DragonBolt", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 27, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 15, ArcaneScaling = 0, LocationId = 172, Image = File.ReadAllBytes("Images/Vyke's Dragonbolt.png") },
            new Spell() { SpellId = 44, Name = "Whirl O Flame", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 21, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 13, ArcaneScaling = 0, LocationId = 121, Image = File.ReadAllBytes("Images/Whirl O Flame!.png") },
            new Spell() { SpellId = 45, Name = "Wrath of Gold", TypeOfSpell = SpellType.Magic, Incantation = true, Scorcery = false, FocusPoints = 40, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 32, ArcaneScaling = 0, LocationId = 118, Image = File.ReadAllBytes("Images/Wrath of Gold.png") },
            new Spell() { SpellId = 46, Name = "Barrier of Gold", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 30, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 24, ArcaneScaling = 0, LocationId = 162, Image = File.ReadAllBytes("Images/Barrier of Gold.png") },
            new Spell() { SpellId = 47, Name = "Bestial Constitution", TypeOfSpell = SpellType.Heal, Incantation = true, Scorcery = false, FocusPoints = 10, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 9, ArcaneScaling = 0, LocationId = 130, Image = File.ReadAllBytes("Images/Bestial Constitution.png") },
            new Spell() { SpellId = 48, Name = "Black Flame", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 15, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 20, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Black Flame.png") },
            new Spell() { SpellId = 49, Name = "Black Flame Blade", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 15, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 17, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Black Flame Blade.png") },
            new Spell() { SpellId = 50, Name = "Black Flame Ritual", TypeOfSpell = SpellType.Fire, Incantation = true, Scorcery = false, FocusPoints = 30, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 42, ArcaneScaling = 0, LocationId = 180, Image = File.ReadAllBytes("Images/Black Flame Ritual.png") },
            new Spell() { SpellId = 51, Name = "BloodFlame Blade", TypeOfSpell = SpellType.Buff, Incantation = true, Scorcery = false, FocusPoints = 20, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 12, ArcaneScaling = 0, LocationId = 95, Image = File.ReadAllBytes("Images/Bloodflame Blade.png") },
            new Spell() { SpellId = 52, Name = "Borealis's Mist", TypeOfSpell = SpellType.Frostbite, Incantation = true, Scorcery = false, FocusPoints = 48, SlotUsage = 1, IntelligenceScaling = 0, FaithScaling = 23, ArcaneScaling = 15, LocationId = 123, Image = File.ReadAllBytes("Images/Borealis's Mist.png") },
            new Spell() { SpellId = 53, Name = "Carian Phalanx", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = true, FocusPoints = 26, SlotUsage = 1, IntelligenceScaling = 34, FaithScaling = 0, ArcaneScaling = 0, LocationId = 183, Image = File.ReadAllBytes("Images/Carian Phalanx.png") },
            new Spell() { SpellId = 54, Name = "N/A", TypeOfSpell = SpellType.Magic, Incantation = false, Scorcery = false, FocusPoints = 0, SlotUsage = 0, IntelligenceScaling = 0, FaithScaling = 0, ArcaneScaling = 0, LocationId = 185, Image = File.ReadAllBytes("Images/nopicture.png") }
            );
            context.ArmorSets.AddOrUpdate(a => a.ArmorSetId, new ArmorSet() { ArmorSetId = 1, Name = "Azur's Glintstoner Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 144, Image = File.ReadAllBytes("Images/Azur's Glintstone Set.png") },
            new ArmorSet() { ArmorSetId = 2, Name = "BullGoat Set", TypeOfArmor = ArmorType.HeavyArmor, Pieces = "Helm,Armor,Gauntlets,Greaves", PhysicalProtection = 45, MagicProtection = 28.9, FireProtection = 29.4, LightProtection = 31, HolyProtection = 27.9, LocationId = 113, Image = File.ReadAllBytes("Images/Bull-Goat Set.png") },
            new ArmorSet() { ArmorSetId = 3, Name = "Lionel's Set", TypeOfArmor = ArmorType.HeavyArmor, Pieces = "Helm,Armor,Gauntlets,Greaves", PhysicalProtection = 38.3, MagicProtection = 29.3, FireProtection = 32.4, LightProtection = 28.2, HolyProtection = 29.3, LocationId = 162, Image = File.ReadAllBytes("Images/Lionel's Set.png") },
            new ArmorSet() { ArmorSetId = 4, Name = "OmenKiller Set", TypeOfArmor = ArmorType.MediumArmor, Pieces = "Helm,Armor,Gauntlets,Greaves", PhysicalProtection = 19, MagicProtection = 18, FireProtection = 20.6, LightProtection = 24.7, HolyProtection = 22.1, LocationId = 162, Image = File.ReadAllBytes("Images/Omenkiller Set.png") },
            new ArmorSet() { ArmorSetId = 5, Name = "Raya Lucarian Sorcerer Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes,Leggings", PhysicalProtection = 10.9, MagicProtection = 16.5, FireProtection = 23.5, LightProtection = 11.5, HolyProtection = 20.9, LocationId = 99, Image = File.ReadAllBytes("Images/Raya Lucarian Sorcerer Set.png") },
            new ArmorSet() { ArmorSetId = 6, Name = "Royal Remains Set", TypeOfArmor = ArmorType.HeavyArmor, Pieces = "Helm,Armor,Gauntlets,Greaves", PhysicalProtection = 25.8, MagicProtection = 20.6, FireProtection = 22.1, LightProtection = 17.2, HolyProtection = 19, LocationId = 183, Image = File.ReadAllBytes("Images/Royal Remains Set.png") },
            new ArmorSet() { ArmorSetId = 7, Name = "Spellblade Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Hat,Attire,Gloves,Trousers", PhysicalProtection = 9.2, MagicProtection = 27.6, FireProtection = 24.6, LightProtection = 25.7, HolyProtection = 27.6, LocationId = 183, Image = File.ReadAllBytes("Images/Spellblade Set.png") },
            new ArmorSet() { ArmorSetId = 8, Name = "Alberich's Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Hat,Robe,Bracers,Trousers", PhysicalProtection = 11.4, MagicProtection = 27.9, FireProtection = 25.8, LightProtection = 27.1, HolyProtection = 27.9, LocationId = 162, Image = File.ReadAllBytes("Images/Alberich's Set.png") },
            new ArmorSet() { ArmorSetId = 9, Name = "All-Knowing Set", TypeOfArmor = ArmorType.HeavyArmor, Pieces = "Helm,Armor,Gauntlets,Greaves", PhysicalProtection = 18.1, MagicProtection = 27, FireProtection = 20.6, LightProtection = 22.1, HolyProtection = 19, LocationId = 162, Image = File.ReadAllBytes("Images/All-Knowing Set.png") },
            new ArmorSet() { ArmorSetId = 10, Name = "Banished Knight Set", TypeOfArmor = ArmorType.HeavyArmor, Pieces = "Helm,Armor,Gauntlets,Greaves", PhysicalProtection = 39.3, MagicProtection = 29, FireProtection = 29.2, LightProtection = 28, HolyProtection = 28.5, LocationId = 123, Image = File.ReadAllBytes("Images/Banished Knight Set.png") },
            new ArmorSet() { ArmorSetId = 11, Name = "Blue Silver Set", TypeOfArmor = ArmorType.MediumArmor, Pieces = "Hood,Skirt,Bracelets", PhysicalProtection = 25.7, MagicProtection = 22.2, FireProtection = 20.6, LightProtection = 15.5, HolyProtection = 15.5, LocationId = 164, Image = File.ReadAllBytes("Images/Blue Silver Set.png") },
            new ArmorSet() { ArmorSetId = 12, Name = "Crucible Set", TypeOfArmor = ArmorType.HeavyArmor, Pieces = "Helm,Armor,Gauntlets,Greaves", PhysicalProtection = 38.3, MagicProtection = 28.2, FireProtection = 27.9, LightProtection = 24.7, HolyProtection = 29.3, LocationId = 102, Image = File.ReadAllBytes("Images/Crucible Set.png") },
            new ArmorSet() { ArmorSetId = 13, Name = "Crucible Tree Set", TypeOfArmor = ArmorType.HeavyArmor, Pieces = "Helm,Armor", PhysicalProtection = 38.3, MagicProtection = 28.2, FireProtection = 27.9, LightProtection = 24.7, HolyProtection = 29.3, LocationId = 102, Image = File.ReadAllBytes("Images/Crucible Tree Set.png") },
            new ArmorSet() { ArmorSetId = 14, Name = "Elden Lord Set", TypeOfArmor = ArmorType.MediumArmor, Pieces = "Helm,Armor,Gauntlets,Greaves", PhysicalProtection = 25.1, MagicProtection = 17.9, FireProtection = 24, LightProtection = 14.1, HolyProtection = 16.2, LocationId = 184, Image = File.ReadAllBytes("Images/Elden Lord Set.png") },
            new ArmorSet() { ArmorSetId = 15, Name = "Lusat's Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 124, Image = File.ReadAllBytes("Images/Lusat's Set.png") }
            );
            /*new ArmorSet() { ArmorSetId = 16, Name = "Azur's Glintstoner Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 144, Image = File.ReadAllBytes("") },
            new ArmorSet() { ArmorSetId = 17, Name = "Azur's Glintstoner Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 144, Image = File.ReadAllBytes("") },
            new ArmorSet() { ArmorSetId = 18, Name = "Azur's Glintstoner Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 144, Image = File.ReadAllBytes("") },
            new ArmorSet() { ArmorSetId = 19, Name = "Azur's Glintstoner Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 144, Image = File.ReadAllBytes("") },
            new ArmorSet() { ArmorSetId = 20, Name = "Azur's Glintstoner Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 144, Image = File.ReadAllBytes("") },
            new ArmorSet() { ArmorSetId = 21, Name = "Azur's Glintstoner Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 144, Image = File.ReadAllBytes("") },
            new ArmorSet() { ArmorSetId = 22, Name = "Azur's Glintstoner Set", TypeOfArmor = ArmorType.LightArmor, Pieces = "Crown,Robe,Manchettes", PhysicalProtection = 10.9, MagicProtection = 24.6, FireProtection = 20.2, LightProtection = 20.6, HolyProtection = 22, LocationId = 144, Image = File.ReadAllBytes("") }*/
            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.
        }
    }
}
